import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.49.0';
import {LOGIN_DOMAIN,SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL} from './config.js';
import {filterEmployees,MONTHS,sortEmployees} from './model.js';
import {generateAttendancePdf} from './pdf.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const state={session:null,employees:[],units:[],history:[],selected:new Set(),pdf:null,pdfUrl:null,busy:false};
const NOTICES=[{title:'Renovação de receitas',description:'Orientações sobre entrega, renovação e retirada de receitas na UBSF Nova Sertânia.',image:'assets/avisos/renovacao-de-receitas.png',pdf:'assets/avisos/renovacao-de-receitas.pdf',canva:'https://www.canva.com/d/NsHnyBW79MKNyRI',format:'A4 retrato'}];
const $=selector=>document.querySelector(selector);const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message,type='success'){const item=document.createElement('div');item.className='toast '+type;item.textContent=message;$('#toast').append(item);setTimeout(()=>item.remove(),4200);}
function usernameEmail(username){return `${String(username).trim().toLowerCase().replace(/[^a-z0-9._-]/g,'')}@${LOGIN_DOMAIN}`;}
function showLogin(){state.session=null;$('#loading').hidden=true;$('#app-view').hidden=true;$('#login-view').hidden=false;$('#login-user').focus();}
function showApp(){$('#loading').hidden=true;$('#login-view').hidden=true;$('#app-view').hidden=false;$('#current-user').textContent=state.session.user.user_metadata?.username||'RWXV';route();}
async function loadData(){
 const [employees,units,history]=await Promise.all([
  supabase.from('fp_employees').select('*,unit:fp_units(*)').order('name'),
  supabase.from('fp_units').select('*').order('name'),
  supabase.from('fp_generation_logs').select('*').order('created_at',{ascending:false}).limit(80)
 ]);
 for(const result of [employees,units,history])if(result.error)throw result.error;
 state.employees=employees.data||[];state.units=units.data||[];state.history=history.data||[];
 state.selected=new Set([...state.selected].filter(id=>state.employees.some(e=>e.id===id&&e.active)));
}
async function boot(){
 const {data:{session}}=await supabase.auth.getSession();if(!session)return showLogin();
 state.session=session;try{await loadData();showApp();}catch(error){console.error(error);toast('Não foi possível carregar os dados: '+error.message,'error');showApp();}
}
function closeSidebar(){document.body.classList.remove('sidebar-open');}
function setActiveNav(route){document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));}
function route(){const name=location.hash.replace('#','')||'inicio';setActiveNav(name);closeSidebar();({inicio:renderHome,gerar:renderGenerator,avisos:renderNotices,colaboradores:renderEmployees,unidades:renderUnits,historico:renderHistory}[name]||renderHome)();}
function pageHeader(kicker,title,description,action=''){return `<header class="page-header"><div><span class="eyebrow">${esc(kicker)}</span><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${action}</header>`;}
function selectOptions(list,value,label='name'){return list.map(item=>`<option value="${esc(item.id)}" ${item.id===value?'selected':''}>${esc(item[label])}</option>`).join('');}
function monthControls(){const now=new Date(),month=Number(sessionStorage.getItem('fp-month')||now.getMonth()+1),year=Number(sessionStorage.getItem('fp-year')||now.getFullYear());return {month,year};}
function renderHome(){
 const active=state.employees.filter(e=>e.active).length;
 $('#workspace').innerHTML=`${pageHeader('UBSF NOVA SERTÂNIA','Serviços da unidade','Acesse documentos, cadastros e materiais de comunicação em um só lugar.',`<div class="header-stats"><b>${active}<small>colaboradores</small></b><b>${NOTICES.length}<small>aviso disponível</small></b></div>`)}<section class="service-grid"><a class="service-card featured" href="#gerar"><span class="service-icon">▣</span><small>GESTÃO DE FREQUÊNCIA</small><h2>Folha de ponto</h2><p>Gere folhas individuais ou um único PDF com os colaboradores selecionados.</p><b>Acessar serviço →</b></a><a class="service-card" href="#avisos"><span class="service-icon blue">◫</span><small>COMUNICAÇÃO</small><h2>Avisos para impressão</h2><p>Visualize e baixe as artes oficiais da unidade em PDF A4.</p><b>Ver materiais →</b></a><a class="service-card" href="#colaboradores"><span class="service-icon amber">♙</span><small>CADASTRO FUNCIONAL</small><h2>Colaboradores</h2><p>Mantenha nomes, cargos, situações e unidades sempre atualizados.</p><b>Gerenciar cadastros →</b></a></section><section class="home-highlight"><div><span class="eyebrow">NOVO MATERIAL</span><h2>Renovação de receitas</h2><p>A nova arte está pronta para impressão em A4 e também disponível para edição no Canva.</p><div><a class="primary" href="#avisos">Visualizar aviso</a><a class="secondary" href="${NOTICES[0].pdf}" download>Baixar PDF</a></div></div><img src="${NOTICES[0].image}" alt="Prévia do aviso sobre renovação de receitas"></section>`;
}
function renderNotices(){
 $('#workspace').innerHTML=`${pageHeader('MATERIAIS DA UNIDADE','Avisos para impressão','Artes oficiais em PDF A4, prontas para baixar, imprimir ou editar no Canva.') }<section class="notice-grid">${NOTICES.map(notice=>`<article class="notice-card"><div class="notice-preview"><img src="${notice.image}" alt="${esc(notice.title)}"><span>${esc(notice.format)}</span></div><div class="notice-content"><span class="eyebrow">AVISO À COMUNIDADE</span><h2>${esc(notice.title)}</h2><p>${esc(notice.description)}</p><div class="notice-actions"><a class="primary" href="${notice.pdf}" download>↓ Baixar PDF</a><a class="secondary" href="${notice.pdf}" target="_blank" rel="noopener">Visualizar</a><a class="canva-button" href="${notice.canva}" target="_blank" rel="noopener">Editar no Canva</a></div></div></article>`).join('')}</section>`;
}
function renderGenerator(){
 const {month,year}=monthControls(),active=sortEmployees(state.employees.filter(e=>e.active));
 $('#workspace').innerHTML=`${pageHeader('FOLHA DE PONTO','Gerar folhas de frequência','Escolha o período e os colaboradores. Cada pessoa ocupará uma página A4.',`<div class="header-stats"><b>${state.employees.filter(e=>e.active).length}<small>ativos</small></b><b>${state.units.filter(u=>u.active).length}<small>unidades</small></b><b>${state.selected.size}<small>selecionados</small></b></div>`)}
 <section class="generator-grid"><article class="panel setup-panel"><header><span class="step">1</span><div><h2>Período da folha</h2><p>O calendário e os dias da semana são preenchidos automaticamente.</p></div></header><div class="form-grid"><label>Mês<select id="reference-month">${MONTHS.map((m,i)=>`<option value="${i+1}" ${i+1===month?'selected':''}>${m}</option>`).join('')}</select></label><label>Ano<input id="reference-year" type="number" min="2020" max="2100" value="${year}"></label></div></article>
 <article class="panel selection-panel"><header><span class="step">2</span><div><h2>Selecionar colaboradores</h2><p>Gere uma folha individual pelo seletor ou monte um PDF unificado.</p></div></header><div class="individual-box"><div><span class="document-icon">▱</span><p><strong>Folha individual</strong><small>Escolha um colaborador</small></p></div><select id="individual-employee"><option value="">Selecione o colaborador…</option>${active.map(e=>`<option value="${e.id}">${esc(e.name)} — ${esc(e.job_title)}</option>`).join('')}</select><button class="primary compact" id="generate-individual" disabled>Gerar individual</button></div><div class="section-divider"><span>PDF UNIFICADO</span></div><div class="selection-tools"><label class="search-field"><span>⌕</span><input id="employee-search" type="search" placeholder="Buscar nome, cargo ou situação…"></label><select id="employee-unit-filter"><option value="">Todas as unidades</option>${selectOptions(state.units.filter(u=>u.active),'')}</select><button class="secondary compact" id="select-visible">Selecionar visíveis</button><button class="ghost compact" id="clear-selection">Limpar</button></div><div id="employee-picker" class="employee-picker"></div></article>
 <aside class="panel summary-panel"><span class="eyebrow">RESUMO</span><h2 id="selection-count">${state.selected.size} selecionado(s)</h2><div id="selection-summary" class="selection-summary"></div><button class="primary wide" id="generate-pdf" ${state.selected.size?'':'disabled'}>▣ Gerar ${state.selected.size===1?'PDF individual':'PDF unificado'}</button><small>O PDF será pré-visualizado antes do download.</small></aside></section>`;
 const refresh=()=>{const rows=filterEmployees(active,{query:$('#employee-search').value,unitId:$('#employee-unit-filter').value,status:'active'});$('#employee-picker').innerHTML=rows.map(employee=>`<label class="employee-option ${state.selected.has(employee.id)?'selected':''}"><input type="checkbox" value="${employee.id}" ${state.selected.has(employee.id)?'checked':''}><span class="employee-initial">${esc(employee.name[0])}</span><span><strong>${esc(employee.name)}</strong><small>${esc(employee.job_title)} · ${esc(employee.employment_status)}</small><em>${esc(employee.unit?.name||'Sem unidade')}</em></span><i>✓</i></label>`).join('')||'<div class="empty-state">Nenhum colaborador encontrado.</div>';updateSummary();};
 const updateSummary=()=>{const chosen=active.filter(e=>state.selected.has(e.id));$('#selection-count').textContent=`${chosen.length} selecionado(s)`;$('#selection-summary').innerHTML=chosen.slice(0,6).map(e=>`<div><span>${esc(e.name[0])}</span><p><strong>${esc(e.name)}</strong><small>${esc(e.job_title)}</small></p><button data-remove="${e.id}" aria-label="Remover ${esc(e.name)}">×</button></div>`).join('')+(chosen.length>6?`<p class="more">+ ${chosen.length-6} colaborador(es)</p>`:'')||'<div class="empty-selection"><span>♙</span><p>Sua seleção aparecerá aqui.</p></div>';const button=$('#generate-pdf');button.disabled=!chosen.length;button.textContent=`▣ Gerar ${chosen.length===1?'PDF individual':'PDF unificado'}`;document.querySelector('.header-stats b:last-child').firstChild.textContent=chosen.length;};
 $('#employee-search').oninput=refresh;$('#employee-unit-filter').onchange=refresh;$('#employee-picker').onchange=e=>{if(!e.target.matches('input'))return;e.target.checked?state.selected.add(e.target.value):state.selected.delete(e.target.value);refresh();};
 $('#individual-employee').onchange=e=>{$('#generate-individual').disabled=!e.target.value;};$('#generate-individual').onclick=()=>{const employee=active.find(e=>e.id===$('#individual-employee').value);if(employee)createPdf([employee],$('#generate-individual'));};
 $('#selection-summary').onclick=e=>{const id=e.target.dataset.remove;if(id){state.selected.delete(id);refresh();}};
 $('#select-visible').onclick=()=>{document.querySelectorAll('#employee-picker input').forEach(input=>state.selected.add(input.value));refresh();};$('#clear-selection').onclick=()=>{state.selected.clear();refresh();};
 $('#generate-pdf').onclick=()=>createPdf(active.filter(e=>state.selected.has(e.id)),$('#generate-pdf'));refresh();
}
async function createPdf(employees,button=$('#generate-pdf')){
 if(state.busy||!employees.length)return;state.busy=true;const oldText=button.textContent;button.disabled=true;button.textContent='Gerando documento…';
 const month=Number($('#reference-month').value),year=Number($('#reference-year').value);sessionStorage.setItem('fp-month',month);sessionStorage.setItem('fp-year',year);
 try{const pdf=await generateAttendancePdf(employees,{month,year});state.pdf=pdf;if(state.pdfUrl)URL.revokeObjectURL(state.pdfUrl);state.pdfUrl=URL.createObjectURL(pdf.blob);$('#preview-frame').src=state.pdfUrl;$('#preview-title').textContent=pdf.filename;$('#pdf-preview').hidden=false;document.body.classList.add('modal-open');
  const {error}=await supabase.from('fp_generation_logs').insert({user_id:state.session.user.id,generation_type:employees.length===1?'individual':'unified',reference_month:`${year}-${String(month).padStart(2,'0')}-01`,employee_ids:employees.map(e=>e.id),employee_count:employees.length,file_name:pdf.filename});if(error)console.warn(error);await loadData();
 }catch(error){console.error(error);toast(error.message,'error');}finally{state.busy=false;if(button.isConnected){button.disabled=false;button.textContent=oldText;}}
}
function renderEmployees(){
 $('#workspace').innerHTML=`${pageHeader('CADASTRO FUNCIONAL','Colaboradores','Mantenha os dados que aparecem nas folhas de frequência.',`<button class="primary" id="new-employee">＋ Novo colaborador</button>`)}<section class="panel table-panel"><div class="table-tools"><label class="search-field"><span>⌕</span><input id="table-search" type="search" placeholder="Buscar colaborador…"></label><select id="table-unit"><option value="">Todas as unidades</option>${selectOptions(state.units,'')}</select><span>${state.employees.length} cadastro(s)</span></div><div class="responsive-table"><table><thead><tr><th>Colaborador</th><th>Matrícula</th><th>Cargo</th><th>Situação</th><th>Unidade</th><th>Status</th><th></th></tr></thead><tbody id="employees-body"></tbody></table></div></section>`;
 const refresh=()=>{$('#employees-body').innerHTML=filterEmployees(state.employees,{query:$('#table-search').value,unitId:$('#table-unit').value,status:'all'}).map(e=>`<tr><td data-label="Colaborador"><div class="person-cell"><span>${esc(e.name[0])}</span><strong>${esc(e.name)}</strong></div></td><td data-label="Matrícula">${esc(e.registration||'—')}</td><td data-label="Cargo">${esc(e.job_title)}</td><td data-label="Situação"><span class="tag">${esc(e.employment_status)}</span></td><td data-label="Unidade">${esc(e.unit?.name||'—')}</td><td data-label="Status"><span class="status ${e.active?'active':'inactive'}">${e.active?'Ativo':'Inativo'}</span></td><td><button class="row-action" data-edit="${e.id}">Editar</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty-state">Nenhum colaborador encontrado.</td></tr>';};
 $('#new-employee').onclick=()=>openEmployee();$('#table-search').oninput=refresh;$('#table-unit').onchange=refresh;$('#employees-body').onclick=e=>{const id=e.target.dataset.edit;if(id)openEmployee(id);};refresh();
}
function openEmployee(id=''){
 const employee=state.employees.find(e=>e.id===id);openModal(employee?'EDITAR CADASTRO':'NOVO CADASTRO',employee?'Editar colaborador':'Novo colaborador','Os dados abaixo serão impressos na folha de frequência.',`<form id="employee-form"><div class="form-grid"><label class="span-2">Nome completo<input id="employee-name" required maxlength="160" value="${esc(employee?.name||'')}"></label><label>Matrícula<input id="employee-registration" maxlength="40" value="${esc(employee?.registration||'')}"></label><label>Cargo<input id="employee-job" required maxlength="100" value="${esc(employee?.job_title||'')}"></label><label>Situação funcional<input id="employee-status" required maxlength="80" list="status-options" value="${esc(employee?.employment_status||'')}"><datalist id="status-options"><option>BCC</option><option>CONTRATO</option><option>EFETIVO</option><option>PROGRAMA MAIS MÉDICO</option></datalist></label><label>Unidade<select id="employee-unit" required><option value="">Selecione…</option>${selectOptions(state.units.filter(u=>u.active),employee?.unit_id||'')}</select></label><label class="span-2">Observações da folha<textarea id="employee-observations" rows="3" maxlength="500">${esc(employee?.observations||'')}</textarea></label><label class="switch span-2"><input id="employee-active" type="checkbox" ${employee?.active===false?'':'checked'}><span></span>Colaborador ativo</label></div><div class="modal-actions"><button type="button" class="secondary" data-close>Cancelar</button><button type="submit" class="primary">Salvar colaborador</button></div></form>`);
 $('#employee-form').onsubmit=async event=>{event.preventDefault();const payload={name:$('#employee-name').value.trim().toUpperCase(),registration:$('#employee-registration').value.trim().toUpperCase()||null,job_title:$('#employee-job').value.trim().toUpperCase(),employment_status:$('#employee-status').value.trim().toUpperCase(),unit_id:$('#employee-unit').value,observations:$('#employee-observations').value.trim()||null,active:$('#employee-active').checked};await saveRecord('fp_employees',id,payload,'Colaborador salvo.');};
}
function renderUnits(){
 $('#workspace').innerHTML=`${pageHeader('ESTRUTURA MUNICIPAL','Unidades e setores','Cadastre os locais de trabalho que aparecem no cabeçalho da folha.',`<button class="primary" id="new-unit">＋ Nova unidade</button>`)}<div class="unit-grid">${state.units.map(unit=>`<article class="unit-card"><div><span>▥</span><small>${esc(unit.secretariat)}</small><h2>${esc(unit.name)}</h2><p>${state.employees.filter(e=>e.unit_id===unit.id&&e.active).length} colaborador(es) ativo(s)</p></div><footer><span class="status ${unit.active?'active':'inactive'}">${unit.active?'Ativa':'Inativa'}</span><button class="row-action" data-edit-unit="${unit.id}">Editar</button></footer></article>`).join('')||'<div class="empty-state">Nenhuma unidade cadastrada.</div>'}</div>`;
 $('#new-unit').onclick=()=>openUnit();$('#workspace').onclick=e=>{const id=e.target.dataset.editUnit;if(id)openUnit(id);};
}
function openUnit(id=''){
 const unit=state.units.find(u=>u.id===id);openModal(unit?'EDITAR UNIDADE':'NOVA UNIDADE',unit?'Editar unidade':'Cadastrar unidade','O nome e a secretaria serão impressos no cabeçalho.',`<form id="unit-form"><div class="form-grid"><label class="span-2">Secretaria<input id="unit-secretariat" required maxlength="120" value="${esc(unit?.secretariat||'SECRETARIA DE SAÚDE')}"></label><label class="span-2">Unidade / setor<input id="unit-name" required maxlength="140" value="${esc(unit?.name||'')}"></label><label class="switch span-2"><input id="unit-active" type="checkbox" ${unit?.active===false?'':'checked'}><span></span>Unidade ativa</label></div><div class="modal-actions"><button type="button" class="secondary" data-close>Cancelar</button><button type="submit" class="primary">Salvar unidade</button></div></form>`);
 $('#unit-form').onsubmit=async event=>{event.preventDefault();await saveRecord('fp_units',id,{secretariat:$('#unit-secretariat').value.trim().toUpperCase(),name:$('#unit-name').value.trim().toUpperCase(),active:$('#unit-active').checked},'Unidade salva.');};
}
async function saveRecord(table,id,payload,message){
 if(state.busy)return;state.busy=true;try{const query=id?supabase.from(table).update(payload).eq('id',id):supabase.from(table).insert(payload);const {error}=await query;if(error)throw error;await loadData();closeModal();toast(message);route();}catch(error){toast('Não foi possível salvar: '+error.message,'error');}finally{state.busy=false;}
}
function renderHistory(){
 $('#workspace').innerHTML=`${pageHeader('AUDITORIA','Histórico de geração','Registro dos PDFs gerados pelo sistema.')}<section class="panel history-list">${state.history.map(item=>`<article><span class="history-icon">${item.generation_type==='individual'?'▱':'▤'}</span><div><strong>${esc(item.file_name)}</strong><small>${item.employee_count} colaborador(es) · ${new Date(item.reference_month+'T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</small></div><time>${new Date(item.created_at).toLocaleString('pt-BR')}</time><span class="tag">${item.generation_type==='individual'?'Individual':'Unificado'}</span></article>`).join('')||'<div class="empty-state">Nenhum documento gerado ainda.</div>'}</section>`;
}
function openModal(kicker,title,subtitle,body){$('#modal-kicker').textContent=kicker;$('#modal-title').textContent=title;$('#modal-subtitle').textContent=subtitle;$('#modal-body').innerHTML=body;$('#modal').hidden=false;document.body.classList.add('modal-open');$('#modal-body [data-close]')?.addEventListener('click',closeModal);}
function closeModal(){$('#modal').hidden=true;document.body.classList.remove('modal-open');}

$('#login-form').onsubmit=async event=>{event.preventDefault();const button=$('#login-submit');button.disabled=true;button.textContent='Entrando…';$('#login-error').textContent='';const {data,error}=await supabase.auth.signInWithPassword({email:usernameEmail($('#login-user').value),password:$('#login-password').value});if(error){$('#login-error').textContent='Usuário ou senha inválidos.';button.disabled=false;button.textContent='Entrar no sistema';return;}state.session=data.session;await loadData();showApp();button.disabled=false;button.textContent='Entrar no sistema';};
$('#toggle-password').onclick=()=>{const input=$('#login-password');input.type=input.type==='password'?'text':'password';};
$('#logout-button').onclick=async()=>{await supabase.auth.signOut();showLogin();};$('#menu-toggle').onclick=()=>document.body.classList.toggle('sidebar-open');$('#sidebar-backdrop').onclick=closeSidebar;window.addEventListener('hashchange',route);
$('#modal-close').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal();};$('#preview-close').onclick=()=>{$('#pdf-preview').hidden=true;document.body.classList.remove('modal-open');};$('#preview-download').onclick=()=>{if(!state.pdf)return;const a=document.createElement('a');a.href=state.pdfUrl;a.download=state.pdf.filename;a.click();toast('PDF baixado com sucesso.');};
supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')showLogin();else if(session)state.session=session;});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));boot();
